### ISSUE TITLE
Docker image: PHP out of memory

### ISSUE THREAD

**Issue by agileben** [j6s/shape-up-downloader#6]
Getting error in the logs: mmap() failed: [12] Cannot allocate memory
Fatal error: Out of memory (allocated 12230656) (tried to allocate 7329472 bytes) in /app/src/DownloadSingleHtmlCommand.php on line 63

New to docker, but I suspect I could try adding the following to the Dockerfile if I can figure out how to rebuild the image: 

#dockerfile
RUN cd /usr/local/etc/php/conf.d/ && \
  echo 'memory_limit = -1' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini

**Comment by j6s** [comment]
I am sorry, I must have missed this issue in my mailbox. I'll look into this.

**Comment by j6s** [comment]
While I could not replicate the issue, I added an unlimited memory_limit to the new docker image. It should be available now as `thej6s/shape-up-downloader:latest` and `thej6s/shape-up-downloader:1.1.0`.
